"""tables fixes

Revision ID: 09fb6f6fd1c9
Revises: c8d520a43015
Create Date: 2024-11-20 14:12:33.082038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fb6f6fd1c9'
down_revision: Union[str, None] = 'c8d520a43015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coefficient_match_id_fkey', 'coefficient', type_='foreignkey')
    op.create_foreign_key(None, 'coefficient', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('match_name_key', 'match', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('match_name_key', 'match', ['name'])
    op.drop_constraint(None, 'coefficient', type_='foreignkey')
    op.create_foreign_key('coefficient_match_id_fkey', 'coefficient', 'match', ['match_id'], ['id'])
    # ### end Alembic commands ###
