"""match table fix

Revision ID: 2958c4aac0d3
Revises: c97d9716d3b3
Create Date: 2024-11-19 13:11:27.528028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2958c4aac0d3'
down_revision: Union[str, None] = 'c97d9716d3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'match', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='unique')
    # ### end Alembic commands ###
