"""match table fix

Revision ID: c8d520a43015
Revises: 2958c4aac0d3
Create Date: 2024-11-19 14:25:41.887650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d520a43015'
down_revision: Union[str, None] = '2958c4aac0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coefficient', 'is_ended_soon')
    op.drop_column('match', 'is_ended')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('is_ended', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('coefficient', sa.Column('is_ended_soon', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
