"""init tables

Revision ID: c97d9716d3b3
Revises: 
Create Date: 2024-11-19 11:02:49.425730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97d9716d3b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_ended', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('score_game', sa.String(length=10), nullable=True),
    sa.Column('total_point', sa.String(length=10), nullable=True),
    sa.Column('total_bet_0', sa.String(length=10), nullable=True),
    sa.Column('total_bet_1', sa.String(length=10), nullable=True),
    sa.Column('handicap_point_0', sa.String(length=10), nullable=True),
    sa.Column('handicap_bet_0', sa.String(length=10), nullable=True),
    sa.Column('handicap_point_1', sa.String(length=10), nullable=True),
    sa.Column('handicap_bet_1', sa.String(length=10), nullable=True),
    sa.Column('time_game', sa.String(length=10), nullable=True),
    sa.Column('server_time', sa.String(length=10), nullable=True),
    sa.Column('is_ended_soon', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coefficient')
    op.drop_table('match')
    op.drop_table('league')
    # ### end Alembic commands ###
